# Generated by Django 5.0 on 2023-12-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='path',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
