# Generated by Django 5.0 on 2023-12-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom_API', '0004_rename_name_filedata_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='filepath',
            field=models.FileField(upload_to='../uploads/'),
        ),
    ]
