# Generated by Django 5.0 on 2023-12-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom_API', '0005_alter_filedata_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='filepath',
            field=models.FileField(upload_to='./uploads/'),
        ),
    ]
